name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['22.x']
        os: [ubuntu-latest]

    steps:
      - name: Config Git (Mainly for Windows)
        run: git config --global core.autocrlf false

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: install Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Lint code
        run: pnpm lint
#      - name: Test
#        run: pnpm test --ci --coverage --maxWorkers=2
